# Generated by Django 4.2 on 2023-05-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_writers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Writers',
            new_name='Writer',
        ),
    ]
