# Generated by Django 4.2 on 2023-05-14 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_writers_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='info',
        ),
    ]
