# Generated by Django 4.2 on 2023-05-14 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_writer_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='info',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
