# Generated by Django 4.2 on 2023-05-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_writer_info'),
    ]

    operations = [
    ]
