# Generated by Django 4.2 on 2023-05-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_add_info_to_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='writer',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
