# Generated by Django 4.2 on 2023-06-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_blogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogs',
            new_name='blog',
        ),
    ]
