# Generated by Django 4.2 on 2023-06-03 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='discription',
            new_name='details',
        ),
    ]
